import { Page, expect } from '@playwright/test';
import { PIMPage } from '../pages/PIMPage';

export class PIMSteps {
  private readonly page: Page;
  private readonly pimPage: PIMPage;

  constructor(page: Page) {
    this.page = page;
    this.pimPage = new PIMPage(page);
  }

  /**
   * Navigate to PIM module
   */
  async navigateToPIM(): Promise<void> {
    await this.pimPage.pimMenuLink.click();
    await this.page.waitForLoadState('domcontentloaded', { timeout: 30000 }).catch(() => undefined);
    await this.page.waitForURL(/pim/i, { timeout: 30000 }).catch(() => undefined);
  }

  /**
   * Navigate to Add Employee page
   */
  async navigateToAddEmployee(url: string): Promise<void> {
    await this.page.goto(url, { waitUntil: 'load' });
  }

  /**
   * Verify employee list is displayed
   */
  async verifyEmployeeListDisplayed(): Promise<void> {
    await expect(this.pimPage.employeeTable).toBeVisible();
  }

/**
 * Verify record count is displayed
 */
async verifyRecordCount(): Promise<void> {

    await expect(this.pimPage.recordsFoundText).toContainText('Records Found');
}

  /**
   * Enter employee name in search field
   */
  async enterEmployeeName(name: string): Promise<void> {
    await this.pimPage.employeeNameSearchField.fill(name);
  }

  /**
   * Enter employee ID in search field
   */
  async enterEmployeeId(id: string): Promise<void> {
    await this.pimPage.employeeIdSearchField.fill(id);
  }

  /**
   * Click Search button
   */
  async clickSearchButton(): Promise<void> {
    await this.pimPage.searchButton.click();
    await this.page.waitForLoadState('load');
  }

  /**
   * Click Reset button
   */
  async clickResetButton(): Promise<void> {
    await this.pimPage.resetButton.click();
    await this.page.waitForLoadState('load');
  }

  /**
   * Click Add Employee button
   */
  async clickAddEmployeeButton(): Promise<void> {
    await this.pimPage.addEmployeeButton.click();
    await this.page.waitForLoadState('domcontentloaded', { timeout: 30000 }).catch(() => undefined);
    await this.page.waitForURL(/addEmployee/i, { timeout: 30000 }).catch(() => undefined);
  }

  /**
   * Enter first name
   */
  async enterFirstName(firstName: string): Promise<void> {
    await this.pimPage.firstNameField.fill(firstName);
  }

  /**
   * Enter middle name
   */
  async enterMiddleName(middleName: string): Promise<void> {
    await this.pimPage.middleNameField.fill(middleName);
  }

  /**
   * Enter last name
   */
  async enterLastName(lastName: string): Promise<void> {
    await this.pimPage.lastNameField.fill(lastName);
  }

  /**
   * Verify employee ID is auto-generated
   */
  async verifyEmployeeIdAutoGenerated(): Promise<void> {
    await expect(this.pimPage.employeeIdField).toBeVisible({ timeout: 15000 });

    const value = await this.pimPage.employeeIdField.inputValue();
    const normalizedValue = (value ?? '').trim();

    console.log(`Auto-generated Employee ID: ${normalizedValue}`);
    expect(normalizedValue, 'Employee ID should be auto-generated and not blank').not.toEqual('');
  }

  /**
   * Check Create Login Details checkbox
   */
  async checkCreateLoginCheckbox(): Promise<void> {
    await this.pimPage.createLoginCheckbox.check();
  }

  /**
   * Verify login fields are visible
   */
  async verifyLoginFieldsVisible(): Promise<void> {
    await expect(this.pimPage.loginFields).toBeVisible();
  }

  /**
   * Enter username for login
   */
  async enterUsername(username: string): Promise<void> {
    await this.pimPage.loginUsernameField.fill(username);
  }

  /**
   * Enter password for login
   */
  async enterPassword(password: string): Promise<void> {
    await this.pimPage.loginPasswordField.fill(password);
  }

  /**
   * Click Save button
   */
  async clickSaveButton(): Promise<void> {
    await this.pimPage.saveButton.click();
    await this.page.waitForLoadState('domcontentloaded', { timeout: 30000 }).catch(() => undefined);
  }

  /**
   * Click Cancel button
   */
  async clickCancelButton(): Promise<void> {
    await this.pimPage.cancelButton.click();
    await this.page.waitForLoadState('load');
  }

  /**
   * Verify employee is created
   */
  async verifyEmployeeCreated(): Promise<void> {
    const toast = this.pimPage.successToast;
    const toastVisible = await toast.isVisible().catch(() => false);

    if (toastVisible) {
      await expect(toast).toContainText(/saved|success|successfully/i, { timeout: 20000 });
    } else {
      await this.page.waitForURL(/pim/i, { timeout: 30000 });
    }
  }

  /**
   * Verify search results are not empty
   */
  async verifySearchResultsNotEmpty(): Promise<void> {
    const count = await this.pimPage.employeeTableRows.count();
    expect(count).toBeGreaterThanOrEqual(0);
  }

  /**
   * Verify filter fields are cleared
   */
  async verifyFilterFieldsCleared(): Promise<void> {
    const fieldValue = await this.pimPage.employeeNameSearchField.inputValue();
    expect(fieldValue).toBe('');
  }

  /**
   * Upload employee photo
   */
  async uploadEmployeePhoto(filePath: string): Promise<void> {
    await this.pimPage.fileUploadInput.setInputFiles(filePath);
  }

  /**
   * Apply Employment Status filter
   */
  async applyEmploymentStatusFilter(status: string): Promise<void> {
    await this.pimPage.employmentStatusDropdown.click();
    await this.pimPage.getTextElement(status).click();
  }

  /**
   * Select employment status from dropdown
   */
  async selectEmploymentStatus(status: string): Promise<void> {
    await this.pimPage.employmentStatusDropdownAlt.click();
    await this.pimPage.getTextElementPartial(status).click();
  }

  /**
   * Verify bulk select functionality
   */
  async verifyBulkSelectCheckbox(): Promise<void> {
    await expect(this.pimPage.tableHeaderCheckbox).toBeVisible();
  }

  /**
   * Select all employees
   */
  async selectAllEmployees(): Promise<void> {
    await this.pimPage.tableHeaderCheckbox.check();
  }

  /**
   * Click table header to sort
   */
  async sortByColumn(columnName: string): Promise<void> {
    await this.pimPage.getColumnHeader(columnName).click();
    await this.page.waitForLoadState('load');
  }

  /**
   * Navigate to next page
   */
  async clickNextPage(): Promise<void> {
    if (await this.pimPage.nextPageButton.isVisible()) {
      await this.pimPage.nextPageButton.click();
      await this.page.waitForLoadState('load');
    }
  }

  /**
   * Navigate to previous page
   */
  async clickPreviousPage(): Promise<void> {
    if (await this.pimPage.previousPageButton.isVisible()) {
      await this.pimPage.previousPageButton.click();
      await this.page.waitForLoadState('load');
    }
  }
}